name: 'cronDon'
version: '1.0.0'
config-version: 2

profile: 'cronDon'

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["models/seeds"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  cronDon:
    staging:
      +materialized: view
    marts:
      +materialized: table
    intermediate:
      +materialized: ephemeral
    kpi:
      +schema: nate_sandbox
      kpi_dim_date:
        +materialized: table
      agg_kpi_dashboard:
        +materialized: incremental
        +on_schema_change: ignore
        +incremental_strategy: merge
    fin_ref:
      +schema: fin_ref

seeds:
  cronDon:
    +schema: nate_sandbox

vars:
  # Add any project-level variables here
  raw_schema: "public"  # Schema where raw data is stored
  
  # KPI Dashboard variables
  dim_date_start: '2015-01-01'
  dim_date_end:   '2035-12-31'
  kpi_dashboard_lookback_days: 730   # supports YoY for 28/MTD/QTD/YTD (2 years of data)
  kpi_dashboard_backfill_days: 1     # recompute today (+ yesterday if you bump this) 