cronDon:
  target: prod_url
  outputs:
    # Primary configuration using DATABASE_URL (recommended for Render)
    prod_url:
      type: postgres
      host: "{{ env_var('DB_HOST') }}"
      port: "{{ env_var('DB_PORT', '5432') | as_native }}"
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      database: "{{ env_var('DB_NAME') }}"
      schema: public
      threads: 4
      keepalives_idle: 0
      connect_timeout: 30
      application_name: dashdon_dbt
      # SSL configuration for Render
      sslmode: require
      