cronDon:
  target: prod_url
  outputs:
    # Primary configuration using DATABASE_URL (recommended for Render)
    prod_url:
      type: postgres
      database: "{{ env_var('DB_NAME') }}"
      url: "{{ env_var('DATABASE_URL') }}"
      schema: analytics
      threads: 4
      keepalives_idle: 0
      search_path: analytics, public
      sslmode: require
      
    # Fallback configuration using individual variables
    prod:
      type: postgres
      host: "{{ env_var('DB_HOST') }}"
      port: "{{ env_var('DB_PORT', '5432') | as_native }}"
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      dbname: "{{ env_var('DB_NAME') }}"
      schema: analytics
      threads: 4
      keepalives_idle: 0
      search_path: analytics, public
      sslmode: require 